// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huakzwguwjulxhvcztuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1YWt6d2d1d2p1bHhodmN6dHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDQzNTQsImV4cCI6MjA2NDQ4MDM1NH0.mTlrd3bYmkBDPjrkLs-3B8eAfdTjjOn7ILj52XS5TpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);